import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/cn";
import { site } from "@/lib/site";

/** Intrinsic size of the generated wordmark files. */
const LOGO_WIDTH = 1200;
const LOGO_HEIGHT = 113;

/**
 * The size the srcset is built around, not the size of the file.
 *
 * The mark is drawn at most 20px tall, so about 212px wide. Passing the
 * intrinsic 1200px alongside a fixed-pixel `sizes` made Next emit all twelve
 * configured widths - up to 1920w - for a wordmark that never exceeds a
 * quarter of that. Each of those is a cache key and, on first request, a cold
 * AVIF encode. Declaring the real render width instead leaves a two-entry
 * srcset at 1x and 2x.
 *
 * Kept on the file's own 10.6:1 ratio so the reserved box still matches.
 */
const RENDER_WIDTH = 318;
const RENDER_HEIGHT = Math.round((RENDER_WIDTH * LOGO_HEIGHT) / LOGO_WIDTH);

/**
 * The wordmark is unusually wide (about 10.6:1), so a fixed pixel height that
 * looks right on desktop eats more than half of a 375px screen. Size it with
 * responsive classes instead.
 */
const SIZES = {
  header: "h-3.5 w-auto sm:h-4 lg:h-5",
  footer: "h-4 w-auto sm:h-5",
} as const;

type BrandMarkProps = {
  /** "dark" renders the charcoal wordmark for light surfaces. */
  tone?: "dark" | "light";
  size?: keyof typeof SIZES;
  className?: string;
  /** Omit the link when the mark sits inside another link or a heading. */
  asLink?: boolean;
  /**
   * Start the download immediately instead of lazily. For a mark that is on
   * screen at first paint.
   *
   * Paired with `fetchPriority="low"` below, which is what actually keeps the
   * mark out of the way. React 19 preloads every server-rendered <img> unless
   * it is lazy or explicitly low priority, so eager loading alone put two
   * <link rel=preload> tags in the head ahead of the hero photograph - the
   * page's real LCP element - and on throttled 4G the hero paid for it. Low
   * priority drops the preload and still starts the download immediately, so
   * the mark never flashes in but never jumps the queue either. It renders
   * fourteen pixels tall; it can afford to wait behind a full-screen photo.
   */
  eager?: boolean;
};

/**
 * The Niscala wordmark.
 *
 * Two variants are generated by the image pipeline from the single supplied
 * PNG: the original white mark for dark and yellow surfaces, and a recoloured
 * charcoal twin for the warm-white surface the site mostly uses.
 */
export function BrandMark({
  tone = "dark",
  size = "header",
  className,
  asLink = true,
  eager = false,
}: BrandMarkProps) {
  const image = (
    <Image
      src={
        tone === "dark"
          ? "/logo/niscala-wordmark-dark.png"
          : "/logo/niscala-wordmark-light.png"
      }
      alt={site.name}
      width={RENDER_WIDTH}
      height={RENDER_HEIGHT}
      loading={eager ? "eager" : "lazy"}
      fetchPriority="low"
      className={SIZES[size]}
    />
  );

  if (!asLink) {
    return <span className={cn("inline-flex items-center", className)}>{image}</span>;
  }

  return (
    <Link
      href="/"
      className={cn("inline-flex items-center", className)}
      aria-label={`${site.name} - beranda`}
    >
      {image}
    </Link>
  );
}
