import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/cn";
import { site } from "@/lib/site";

/** Intrinsic size of the generated wordmark files. */
const LOGO_WIDTH = 1200;
const LOGO_HEIGHT = 113;

/**
 * The wordmark is unusually wide (about 10.6:1), so a fixed pixel height that
 * looks right on desktop eats more than half of a 375px screen. Size it with
 * responsive classes instead.
 */
const SIZES = {
  header: "h-3.5 w-auto sm:h-4 lg:h-5",
  footer: "h-4 w-auto sm:h-5",
} as const;

type BrandMarkProps = {
  /** "dark" renders the charcoal wordmark for light surfaces. */
  tone?: "dark" | "light";
  size?: keyof typeof SIZES;
  className?: string;
  /** Omit the link when the mark sits inside another link or a heading. */
  asLink?: boolean;
  /**
   * Preload the file. Only for a mark that is on screen at first paint - the
   * footer's copy would otherwise queue ahead of the hero photograph, which is
   * the page's actual LCP element.
   */
  priority?: boolean;
};

/**
 * The Niscala wordmark.
 *
 * Two variants are generated by the image pipeline from the single supplied
 * PNG: the original white mark for dark and yellow surfaces, and a recoloured
 * charcoal twin for the warm-white surface the site mostly uses.
 */
export function BrandMark({
  tone = "dark",
  size = "header",
  className,
  asLink = true,
  priority = false,
}: BrandMarkProps) {
  const image = (
    <Image
      src={
        tone === "dark"
          ? "/logo/niscala-wordmark-dark.png"
          : "/logo/niscala-wordmark-light.png"
      }
      alt={site.name}
      width={LOGO_WIDTH}
      height={LOGO_HEIGHT}
      priority={priority}
      sizes="240px"
      className={SIZES[size]}
    />
  );

  if (!asLink) {
    return <span className={cn("inline-flex items-center", className)}>{image}</span>;
  }

  return (
    <Link
      href="/"
      className={cn("inline-flex items-center", className)}
      aria-label={`${site.name} - beranda`}
    >
      {image}
    </Link>
  );
}
